/* tslint:disable */
/* eslint-disable */
/**
 * Onboarding online screens graph models
 * Onboarding online screens graph models and interfaces
 *
 * The version of the OpenAPI document: 1.1.0-alpha.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CheckBoxBlock } from './CheckBoxBlock';
import {
    CheckBoxBlockFromJSON,
    CheckBoxBlockFromJSONTyped,
    CheckBoxBlockToJSON,
} from './CheckBoxBlock';
import type { CheckBoxKind } from './CheckBoxKind';
import {
    CheckBoxKindFromJSON,
    CheckBoxKindFromJSONTyped,
    CheckBoxKindToJSON,
} from './CheckBoxKind';
import type { SelectedCheckBoxBlock } from './SelectedCheckBoxBlock';
import {
    SelectedCheckBoxBlockFromJSON,
    SelectedCheckBoxBlockFromJSONTyped,
    SelectedCheckBoxBlockToJSON,
} from './SelectedCheckBoxBlock';

/**
 * Base checkbox parameters
 * @export
 * @interface BaseCheckBox
 */
export interface BaseCheckBox {
    /**
     * 
     * @type {CheckBoxKind}
     * @memberof BaseCheckBox
     */
    kind: CheckBoxKind;
    /**
     * Flag if checkbox checked
     * @type {boolean}
     * @memberof BaseCheckBox
     */
    checked: boolean;
    /**
     * 
     * @type {CheckBoxBlock}
     * @memberof BaseCheckBox
     */
    styles: CheckBoxBlock;
    /**
     * 
     * @type {SelectedCheckBoxBlock}
     * @memberof BaseCheckBox
     */
    selectedBlock: SelectedCheckBoxBlock;
}

/**
 * Check if a given object implements the BaseCheckBox interface.
 */
export function instanceOfBaseCheckBox(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "kind" in value;
    isInstance = isInstance && "checked" in value;
    isInstance = isInstance && "styles" in value;
    isInstance = isInstance && "selectedBlock" in value;

    return isInstance;
}

export function BaseCheckBoxFromJSON(json: any): BaseCheckBox {
    return BaseCheckBoxFromJSONTyped(json, false);
}

export function BaseCheckBoxFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseCheckBox {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'kind': CheckBoxKindFromJSON(json['kind']),
        'checked': json['checked'],
        'styles': CheckBoxBlockFromJSON(json['styles']),
        'selectedBlock': SelectedCheckBoxBlockFromJSON(json['selectedBlock']),
    };
}

export function BaseCheckBoxToJSON(value?: BaseCheckBox | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'kind': CheckBoxKindToJSON(value.kind),
        'checked': value.checked,
        'styles': CheckBoxBlockToJSON(value.styles),
        'selectedBlock': SelectedCheckBoxBlockToJSON(value.selectedBlock),
    };
}

