/* tslint:disable */
/* eslint-disable */
/**
 * Onboarding online screens graph models
 * Onboarding online screens graph models and interfaces
 *
 * The version of the OpenAPI document: 1.1.0-alpha.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Asset } from './Asset';
import {
    AssetFromJSON,
    AssetFromJSONTyped,
    AssetToJSON,
} from './Asset';
import type { ImageBlock } from './ImageBlock';
import {
    ImageBlockFromJSON,
    ImageBlockFromJSONTyped,
    ImageBlockToJSON,
} from './ImageBlock';

/**
 * Base image parameters
 * @export
 * @interface BaseImage
 */
export interface BaseImage {
    /**
     * Dictionary of localized Asset
     * @type {{ [key: string]: Asset; }}
     * @memberof BaseImage
     */
    l10n: { [key: string]: Asset; };
    /**
     * 
     * @type {ImageBlock}
     * @memberof BaseImage
     */
    styles: ImageBlock;
}

/**
 * Check if a given object implements the BaseImage interface.
 */
export function instanceOfBaseImage(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "l10n" in value;
    isInstance = isInstance && "styles" in value;

    return isInstance;
}

export function BaseImageFromJSON(json: any): BaseImage {
    return BaseImageFromJSONTyped(json, false);
}

export function BaseImageFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseImage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'l10n': (mapValues(json['l10n'], AssetFromJSON)),
        'styles': ImageBlockFromJSON(json['styles']),
    };
}

export function BaseImageToJSON(value?: BaseImage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'l10n': (mapValues(value.l10n, AssetToJSON)),
        'styles': ImageBlockToJSON(value.styles),
    };
}

