/* tslint:disable */
/* eslint-disable */
/**
 * Onboarding online screens graph models
 * Onboarding online screens graph models and interfaces
 *
 * The version of the OpenAPI document: 1.1.0-alpha.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Basic paywall body kind
 * @export
 */
export const BasicPaywallBodyKind = {
    Mask: 'mask',
    Gradient: 'gradient'
} as const;
export type BasicPaywallBodyKind = typeof BasicPaywallBodyKind[keyof typeof BasicPaywallBodyKind];


export function BasicPaywallBodyKindFromJSON(json: any): BasicPaywallBodyKind {
    return BasicPaywallBodyKindFromJSONTyped(json, false);
}

export function BasicPaywallBodyKindFromJSONTyped(json: any, ignoreDiscriminator: boolean): BasicPaywallBodyKind {
    return json as BasicPaywallBodyKind;
}

export function BasicPaywallBodyKindToJSON(value?: BasicPaywallBodyKind | null): any {
    return value as any;
}

