/* tslint:disable */
/* eslint-disable */
/**
 * Onboarding online screens graph models
 * Onboarding online screens graph models and interfaces
 *
 * The version of the OpenAPI document: 1.1.0-alpha.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Basic footer block
 * @export
 * @interface BasicFooterBlock
 */
export interface BasicFooterBlock {
    /**
     * 
     * @type {number}
     * @memberof BasicFooterBlock
     */
    leftButtonWidthPercentage?: number;
    /**
     * Padding left for container
     * @type {number}
     * @memberof BasicFooterBlock
     */
    paddingLeft?: number;
    /**
     * Padding right for container
     * @type {number}
     * @memberof BasicFooterBlock
     */
    paddingRight?: number;
    /**
     * Padding top for container
     * @type {number}
     * @memberof BasicFooterBlock
     */
    paddingTop?: number;
    /**
     * Padding bottom for container
     * @type {number}
     * @memberof BasicFooterBlock
     */
    paddingBottom?: number;
}

/**
 * Check if a given object implements the BasicFooterBlock interface.
 */
export function instanceOfBasicFooterBlock(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BasicFooterBlockFromJSON(json: any): BasicFooterBlock {
    return BasicFooterBlockFromJSONTyped(json, false);
}

export function BasicFooterBlockFromJSONTyped(json: any, ignoreDiscriminator: boolean): BasicFooterBlock {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'leftButtonWidthPercentage': !exists(json, 'leftButtonWidthPercentage') ? undefined : json['leftButtonWidthPercentage'],
        'paddingLeft': !exists(json, 'paddingLeft') ? undefined : json['paddingLeft'],
        'paddingRight': !exists(json, 'paddingRight') ? undefined : json['paddingRight'],
        'paddingTop': !exists(json, 'paddingTop') ? undefined : json['paddingTop'],
        'paddingBottom': !exists(json, 'paddingBottom') ? undefined : json['paddingBottom'],
    };
}

export function BasicFooterBlockToJSON(value?: BasicFooterBlock | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'leftButtonWidthPercentage': value.leftButtonWidthPercentage,
        'paddingLeft': value.paddingLeft,
        'paddingRight': value.paddingRight,
        'paddingTop': value.paddingTop,
        'paddingBottom': value.paddingBottom,
    };
}

