/* tslint:disable */
/* eslint-disable */
/**
 * Onboarding online screens graph models
 * Onboarding online screens graph models and interfaces
 *
 * The version of the OpenAPI document: 1.1.0-alpha.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BoxBlock } from './BoxBlock';
import {
    BoxBlockFromJSON,
    BoxBlockFromJSONTyped,
    BoxBlockToJSON,
} from './BoxBlock';

/**
 * Container for elements
 * @export
 * @interface Box
 */
export interface Box {
    /**
     * 
     * @type {BoxBlock}
     * @memberof Box
     */
    styles: BoxBlock;
}

/**
 * Check if a given object implements the Box interface.
 */
export function instanceOfBox(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "styles" in value;

    return isInstance;
}

export function BoxFromJSON(json: any): Box {
    return BoxFromJSONTyped(json, false);
}

export function BoxFromJSONTyped(json: any, ignoreDiscriminator: boolean): Box {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'styles': BoxBlockFromJSON(json['styles']),
    };
}

export function BoxToJSON(value?: Box | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'styles': BoxBlockToJSON(value.styles),
    };
}

