/* tslint:disable */
/* eslint-disable */
/**
 * Onboarding online screens graph models
 * Onboarding online screens graph models and interfaces
 *
 * The version of the OpenAPI document: 1.1.0-alpha.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Button moving animation
 * @export
 */
export const ButtonMovingAnimation = {
    ButtonMovingAnimation1: 'ButtonMovingAnimation1',
    ButtonMovingAnimation2: 'ButtonMovingAnimation2',
    ButtonMovingAnimation3: 'ButtonMovingAnimation3',
    ButtonMovingAnimation4: 'ButtonMovingAnimation4',
    ButtonMovingAnimation5: 'ButtonMovingAnimation5',
    ButtonMovingAnimation6: 'ButtonMovingAnimation6',
    ButtonMovingAnimation7: 'ButtonMovingAnimation7',
    ButtonMovingAnimation8: 'ButtonMovingAnimation8',
    ButtonMovingAnimation9: 'ButtonMovingAnimation9',
    ButtonMovingAnimation10: 'ButtonMovingAnimation10'
} as const;
export type ButtonMovingAnimation = typeof ButtonMovingAnimation[keyof typeof ButtonMovingAnimation];


export function ButtonMovingAnimationFromJSON(json: any): ButtonMovingAnimation {
    return ButtonMovingAnimationFromJSONTyped(json, false);
}

export function ButtonMovingAnimationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ButtonMovingAnimation {
    return json as ButtonMovingAnimation;
}

export function ButtonMovingAnimationToJSON(value?: ButtonMovingAnimation | null): any {
    return value as any;
}

