/* tslint:disable */
/* eslint-disable */
/**
 * Onboarding online screens graph models
 * Onboarding online screens graph models and interfaces
 *
 * The version of the OpenAPI document: 1.1.0-alpha.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Styles for checkbox
 * @export
 * @interface CheckBoxBlock
 */
export interface CheckBoxBlock {
    /**
     * Color of checkbox
     * @type {string}
     * @memberof CheckBoxBlock
     */
    color?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CheckBoxBlock
     */
    isBackgroundFilled?: boolean;
    /**
     * 
     * @type {number}
     * @memberof CheckBoxBlock
     */
    width?: number;
    /**
     * 
     * @type {number}
     * @memberof CheckBoxBlock
     */
    height?: number;
}

/**
 * Check if a given object implements the CheckBoxBlock interface.
 */
export function instanceOfCheckBoxBlock(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CheckBoxBlockFromJSON(json: any): CheckBoxBlock {
    return CheckBoxBlockFromJSONTyped(json, false);
}

export function CheckBoxBlockFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckBoxBlock {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'color': !exists(json, 'color') ? undefined : json['color'],
        'isBackgroundFilled': !exists(json, 'isBackgroundFilled') ? undefined : json['isBackgroundFilled'],
        'width': !exists(json, 'width') ? undefined : json['width'],
        'height': !exists(json, 'height') ? undefined : json['height'],
    };
}

export function CheckBoxBlockToJSON(value?: CheckBoxBlock | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'color': value.color,
        'isBackgroundFilled': value.isBackgroundFilled,
        'width': value.width,
        'height': value.height,
    };
}

