/* tslint:disable */
/* eslint-disable */
/**
 * Onboarding online screens graph models
 * Onboarding online screens graph models and interfaces
 *
 * The version of the OpenAPI document: 1.1.0-alpha.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Close button appearance kind
 * @export
 */
export const CloseAppearance = {
    Visible: 'visible',
    VisibleAfterTimer: 'visibleAfterTimer'
} as const;
export type CloseAppearance = typeof CloseAppearance[keyof typeof CloseAppearance];


export function CloseAppearanceFromJSON(json: any): CloseAppearance {
    return CloseAppearanceFromJSONTyped(json, false);
}

export function CloseAppearanceFromJSONTyped(json: any, ignoreDiscriminator: boolean): CloseAppearance {
    return json as CloseAppearance;
}

export function CloseAppearanceToJSON(value?: CloseAppearance | null): any {
    return value as any;
}

