/* tslint:disable */
/* eslint-disable */
/**
 * Onboarding online screens graph models
 * Onboarding online screens graph models and interfaces
 *
 * The version of the OpenAPI document: 1.1.0-alpha.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Currency format kind
 * @export
 */
export const CurrencyFormatKind = {
    None: 'None',
    Decimal: 'Decimal',
    Currency: 'Currency',
    Percent: 'Percent',
    Scientific: 'Scientific',
    SpellOut: 'SpellOut',
    Ordinal: 'Ordinal',
    CurrencyIsoCode: 'CurrencyISOCode',
    CurrencyPlural: 'CurrencyPlural',
    CurrencyAccounting: 'CurrencyAccounting'
} as const;
export type CurrencyFormatKind = typeof CurrencyFormatKind[keyof typeof CurrencyFormatKind];


export function CurrencyFormatKindFromJSON(json: any): CurrencyFormatKind {
    return CurrencyFormatKindFromJSONTyped(json, false);
}

export function CurrencyFormatKindFromJSONTyped(json: any, ignoreDiscriminator: boolean): CurrencyFormatKind {
    return json as CurrencyFormatKind;
}

export function CurrencyFormatKindToJSON(value?: CurrencyFormatKind | null): any {
    return value as any;
}

