/* tslint:disable */
/* eslint-disable */
/**
 * Onboarding online screens graph models
 * Onboarding online screens graph models and interfaces
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Styles for dashes page indicator block
 * @export
 * @interface DashesPageIndicatorBlock
 */
export interface DashesPageIndicatorBlock {
    /**
     * 
     * @type {string}
     * @memberof DashesPageIndicatorBlock
     */
    notFilledColor?: string;
    /**
     * 
     * @type {string}
     * @memberof DashesPageIndicatorBlock
     */
    filledColor?: string;
    /**
     * 
     * @type {number}
     * @memberof DashesPageIndicatorBlock
     */
    dashHeight?: number;
    /**
     * 
     * @type {number}
     * @memberof DashesPageIndicatorBlock
     */
    dashesSpacing?: number;
}

/**
 * Check if a given object implements the DashesPageIndicatorBlock interface.
 */
export function instanceOfDashesPageIndicatorBlock(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DashesPageIndicatorBlockFromJSON(json: any): DashesPageIndicatorBlock {
    return DashesPageIndicatorBlockFromJSONTyped(json, false);
}

export function DashesPageIndicatorBlockFromJSONTyped(json: any, ignoreDiscriminator: boolean): DashesPageIndicatorBlock {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'notFilledColor': !exists(json, 'notFilledColor') ? undefined : json['notFilledColor'],
        'filledColor': !exists(json, 'filledColor') ? undefined : json['filledColor'],
        'dashHeight': !exists(json, 'dashHeight') ? undefined : json['dashHeight'],
        'dashesSpacing': !exists(json, 'dashesSpacing') ? undefined : json['dashesSpacing'],
    };
}

export function DashesPageIndicatorBlockToJSON(value?: DashesPageIndicatorBlock | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'notFilledColor': value.notFilledColor,
        'filledColor': value.filledColor,
        'dashHeight': value.dashHeight,
        'dashesSpacing': value.dashesSpacing,
    };
}

