/* tslint:disable */
/* eslint-disable */
/**
 * Onboarding online screens graph models
 * Onboarding online screens graph models and interfaces
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    BasicFooter,
    instanceOfBasicFooter,
    BasicFooterFromJSON,
    BasicFooterFromJSONTyped,
    BasicFooterToJSON,
} from './BasicFooter';
import {
    PaywallFooter,
    instanceOfPaywallFooter,
    PaywallFooterFromJSON,
    PaywallFooterFromJSONTyped,
    PaywallFooterToJSON,
} from './PaywallFooter';

/**
 * @type Footer
 * 
 * @export
 */
export type Footer = BasicFooter | PaywallFooter;

export function FooterFromJSON(json: any): Footer {
    return FooterFromJSONTyped(json, false);
}

export function FooterFromJSONTyped(json: any, ignoreDiscriminator: boolean): Footer {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...BasicFooterFromJSONTyped(json, true), ...PaywallFooterFromJSONTyped(json, true) };
}

export function FooterToJSON(value?: Footer | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfBasicFooter(value)) {
        return BasicFooterToJSON(value as BasicFooter);
    }
    if (instanceOfPaywallFooter(value)) {
        return PaywallFooterToJSON(value as PaywallFooter);
    }

    return {};
}

