/* tslint:disable */
/* eslint-disable */
/**
 * Onboarding online screens graph models
 * Onboarding online screens graph models and interfaces
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Box } from './Box';
import {
    BoxFromJSON,
    BoxFromJSONTyped,
    BoxToJSON,
} from './Box';
import type { Image } from './Image';
import {
    ImageFromJSON,
    ImageFromJSONTyped,
    ImageToJSON,
} from './Image';
import type { Text } from './Text';
import {
    TextFromJSON,
    TextFromJSONTyped,
    TextToJSON,
} from './Text';

/**
 * Structure of full collection item type for regular list
 * @export
 * @interface ItemTypeRegular
 */
export interface ItemTypeRegular {
    /**
     * 
     * @type {Image}
     * @memberof ItemTypeRegular
     */
    image: Image;
    /**
     * 
     * @type {Text}
     * @memberof ItemTypeRegular
     */
    title: Text;
    /**
     * 
     * @type {Box}
     * @memberof ItemTypeRegular
     */
    box: Box;
}

/**
 * Check if a given object implements the ItemTypeRegular interface.
 */
export function instanceOfItemTypeRegular(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "image" in value;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "box" in value;

    return isInstance;
}

export function ItemTypeRegularFromJSON(json: any): ItemTypeRegular {
    return ItemTypeRegularFromJSONTyped(json, false);
}

export function ItemTypeRegularFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemTypeRegular {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'image': ImageFromJSON(json['image']),
        'title': TextFromJSON(json['title']),
        'box': BoxFromJSON(json['box']),
    };
}

export function ItemTypeRegularToJSON(value?: ItemTypeRegular | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'image': ImageToJSON(value.image),
        'title': TextToJSON(value.title),
        'box': BoxToJSON(value.box),
    };
}

