/* tslint:disable */
/* eslint-disable */
/**
 * Onboarding online screens graph models
 * Onboarding online screens graph models and interfaces
 *
 * The version of the OpenAPI document: 1.1.0-alpha.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Action } from './Action';
import {
    ActionFromJSON,
    ActionFromJSONTyped,
    ActionToJSON,
} from './Action';
import type { Box } from './Box';
import {
    BoxFromJSON,
    BoxFromJSONTyped,
    BoxToJSON,
} from './Box';
import type { CheckBox } from './CheckBox';
import {
    CheckBoxFromJSON,
    CheckBoxFromJSONTyped,
    CheckBoxToJSON,
} from './CheckBox';
import type { Image } from './Image';
import {
    ImageFromJSON,
    ImageFromJSONTyped,
    ImageToJSON,
} from './Image';
import type { Text } from './Text';
import {
    TextFromJSON,
    TextFromJSONTyped,
    TextToJSON,
} from './Text';

/**
 * Structure of full collection item type for selection list
 * @export
 * @interface ItemTypeSelection
 */
export interface ItemTypeSelection {
    /**
     * 
     * @type {Image}
     * @memberof ItemTypeSelection
     */
    image: Image;
    /**
     * 
     * @type {Text}
     * @memberof ItemTypeSelection
     */
    title: Text;
    /**
     * 
     * @type {Text}
     * @memberof ItemTypeSelection
     */
    subtitle: Text;
    /**
     * 
     * @type {CheckBox}
     * @memberof ItemTypeSelection
     */
    checkBox: CheckBox;
    /**
     * 
     * @type {Action}
     * @memberof ItemTypeSelection
     */
    action: Action;
    /**
     * 
     * @type {Box}
     * @memberof ItemTypeSelection
     */
    box: Box;
    /**
     * 
     * @type {number}
     * @memberof ItemTypeSelection
     */
    weight: number;
}

/**
 * Check if a given object implements the ItemTypeSelection interface.
 */
export function instanceOfItemTypeSelection(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "image" in value;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "subtitle" in value;
    isInstance = isInstance && "checkBox" in value;
    isInstance = isInstance && "action" in value;
    isInstance = isInstance && "box" in value;
    isInstance = isInstance && "weight" in value;

    return isInstance;
}

export function ItemTypeSelectionFromJSON(json: any): ItemTypeSelection {
    return ItemTypeSelectionFromJSONTyped(json, false);
}

export function ItemTypeSelectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemTypeSelection {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'image': ImageFromJSON(json['image']),
        'title': TextFromJSON(json['title']),
        'subtitle': TextFromJSON(json['subtitle']),
        'checkBox': CheckBoxFromJSON(json['checkBox']),
        'action': ActionFromJSON(json['action']),
        'box': BoxFromJSON(json['box']),
        'weight': json['weight'],
    };
}

export function ItemTypeSelectionToJSON(value?: ItemTypeSelection | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'image': ImageToJSON(value.image),
        'title': TextToJSON(value.title),
        'subtitle': TextToJSON(value.subtitle),
        'checkBox': CheckBoxToJSON(value.checkBox),
        'action': ActionToJSON(value.action),
        'box': BoxToJSON(value.box),
        'weight': value.weight,
    };
}

