/* tslint:disable */
/* eslint-disable */
/**
 * Onboarding online screens graph models
 * Onboarding online screens graph models and interfaces
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Loader kind
 * @export
 */
export const LoaderKind = {
    Circle: 'Circle',
    Line: 'Line',
    LoaderKind1: 'LoaderKind1',
    LoaderKind2: 'LoaderKind2',
    LoaderKind3: 'LoaderKind3',
    LoaderKind4: 'LoaderKind4',
    LoaderKind5: 'LoaderKind5'
} as const;
export type LoaderKind = typeof LoaderKind[keyof typeof LoaderKind];


export function LoaderKindFromJSON(json: any): LoaderKind {
    return LoaderKindFromJSONTyped(json, false);
}

export function LoaderKindFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoaderKind {
    return json as LoaderKind;
}

export function LoaderKindToJSON(value?: LoaderKind | null): any {
    return value as any;
}

