/* tslint:disable */
/* eslint-disable */
/**
 * Onboarding online screens graph models
 * Onboarding online screens graph models and interfaces
 *
 * The version of the OpenAPI document: 1.1.0-alpha.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Styles for loader block
 * @export
 * @interface LoaderBlock
 */
export interface LoaderBlock {
    /**
     * Color for loader
     * @type {string}
     * @memberof LoaderBlock
     */
    color?: string;
    /**
     * Padding left for container
     * @type {number}
     * @memberof LoaderBlock
     */
    paddingLeft?: number;
    /**
     * Padding right for container
     * @type {number}
     * @memberof LoaderBlock
     */
    paddingRight?: number;
    /**
     * Padding top for container
     * @type {number}
     * @memberof LoaderBlock
     */
    paddingTop?: number;
    /**
     * Padding bottom for container
     * @type {number}
     * @memberof LoaderBlock
     */
    paddingBottom?: number;
}

/**
 * Check if a given object implements the LoaderBlock interface.
 */
export function instanceOfLoaderBlock(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LoaderBlockFromJSON(json: any): LoaderBlock {
    return LoaderBlockFromJSONTyped(json, false);
}

export function LoaderBlockFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoaderBlock {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'color': !exists(json, 'color') ? undefined : json['color'],
        'paddingLeft': !exists(json, 'paddingLeft') ? undefined : json['paddingLeft'],
        'paddingRight': !exists(json, 'paddingRight') ? undefined : json['paddingRight'],
        'paddingTop': !exists(json, 'paddingTop') ? undefined : json['paddingTop'],
        'paddingBottom': !exists(json, 'paddingBottom') ? undefined : json['paddingBottom'],
    };
}

export function LoaderBlockToJSON(value?: LoaderBlock | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'color': value.color,
        'paddingLeft': value.paddingLeft,
        'paddingRight': value.paddingRight,
        'paddingTop': value.paddingTop,
        'paddingBottom': value.paddingBottom,
    };
}

