/* tslint:disable */
/* eslint-disable */
/**
 * Onboarding online screens graph models
 * Onboarding online screens graph models and interfaces
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    MediaImage,
    instanceOfMediaImage,
    MediaImageFromJSON,
    MediaImageFromJSONTyped,
    MediaImageToJSON,
} from './MediaImage';
import {
    MediaVideo,
    instanceOfMediaVideo,
    MediaVideoFromJSON,
    MediaVideoFromJSONTyped,
    MediaVideoToJSON,
} from './MediaVideo';

/**
 * @type MediaContent
 * Media content
 * @export
 */
export type MediaContent = MediaImage | MediaVideo;

export function MediaContentFromJSON(json: any): MediaContent {
    return MediaContentFromJSONTyped(json, false);
}

export function MediaContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): MediaContent {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...MediaImageFromJSONTyped(json, true), ...MediaVideoFromJSONTyped(json, true) };
}

export function MediaContentToJSON(value?: MediaContent | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfMediaImage(value)) {
        return MediaImageToJSON(value as MediaImage);
    }
    if (instanceOfMediaVideo(value)) {
        return MediaVideoToJSON(value as MediaVideo);
    }

    return {};
}

