/* tslint:disable */
/* eslint-disable */
/**
 * Onboarding online screens graph models
 * Onboarding online screens graph models and interfaces
 *
 * The version of the OpenAPI document: 1.1.0-alpha.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Media top alignment
 * @export
 */
export const MediaTopAlignment = {
    Top: 'top',
    SafeArea: 'safeArea',
    NavigationBar: 'navigationBar'
} as const;
export type MediaTopAlignment = typeof MediaTopAlignment[keyof typeof MediaTopAlignment];


export function MediaTopAlignmentFromJSON(json: any): MediaTopAlignment {
    return MediaTopAlignmentFromJSONTyped(json, false);
}

export function MediaTopAlignmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): MediaTopAlignment {
    return json as MediaTopAlignment;
}

export function MediaTopAlignmentToJSON(value?: MediaTopAlignment | null): any {
    return value as any;
}

