/* tslint:disable */
/* eslint-disable */
/**
 * Onboarding online screens graph models
 * Onboarding online screens graph models and interfaces
 *
 * The version of the OpenAPI document: 1.1.0-alpha.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Media kind
 * @export
 */
export const MediaKind = {
    Image: 'Image',
    Video: 'Video'
} as const;
export type MediaKind = typeof MediaKind[keyof typeof MediaKind];


export function MediaKindFromJSON(json: any): MediaKind {
    return MediaKindFromJSONTyped(json, false);
}

export function MediaKindFromJSONTyped(json: any, ignoreDiscriminator: boolean): MediaKind {
    return json as MediaKind;
}

export function MediaKindToJSON(value?: MediaKind | null): any {
    return value as any;
}

