/* tslint:disable */
/* eslint-disable */
/**
 * Onboarding online screens graph models
 * Onboarding online screens graph models and interfaces
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BaseVideo } from './BaseVideo';
import {
    BaseVideoFromJSON,
    BaseVideoFromJSONTyped,
    BaseVideoToJSON,
} from './BaseVideo';

/**
 * Media video content
 * @export
 * @interface MediaVideo
 */
export interface MediaVideo {
    /**
     * 
     * @type {BaseVideo}
     * @memberof MediaVideo
     */
    video: BaseVideo;
}

/**
 * Check if a given object implements the MediaVideo interface.
 */
export function instanceOfMediaVideo(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "video" in value;

    return isInstance;
}

export function MediaVideoFromJSON(json: any): MediaVideo {
    return MediaVideoFromJSONTyped(json, false);
}

export function MediaVideoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MediaVideo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'video': BaseVideoFromJSON(json['video']),
    };
}

export function MediaVideoToJSON(value?: MediaVideo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'video': BaseVideoToJSON(value.video),
    };
}

