/* tslint:disable */
/* eslint-disable */
/**
 * Onboarding online screens graph models
 * Onboarding online screens graph models and interfaces
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    BasicNavigationBar,
    instanceOfBasicNavigationBar,
    BasicNavigationBarFromJSON,
    BasicNavigationBarFromJSONTyped,
    BasicNavigationBarToJSON,
} from './BasicNavigationBar';
import {
    PaywallNavigationBar,
    instanceOfPaywallNavigationBar,
    PaywallNavigationBarFromJSON,
    PaywallNavigationBarFromJSONTyped,
    PaywallNavigationBarToJSON,
} from './PaywallNavigationBar';

/**
 * @type NavigationBar
 * Navigation bar
 * @export
 */
export type NavigationBar = BasicNavigationBar | PaywallNavigationBar;

export function NavigationBarFromJSON(json: any): NavigationBar {
    return NavigationBarFromJSONTyped(json, false);
}

export function NavigationBarFromJSONTyped(json: any, ignoreDiscriminator: boolean): NavigationBar {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...BasicNavigationBarFromJSONTyped(json, true), ...PaywallNavigationBarFromJSONTyped(json, true) };
}

export function NavigationBarToJSON(value?: NavigationBar | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfBasicNavigationBar(value)) {
        return BasicNavigationBarToJSON(value as BasicNavigationBar);
    }
    if (instanceOfPaywallNavigationBar(value)) {
        return PaywallNavigationBarToJSON(value as PaywallNavigationBar);
    }

    return {};
}

