/* tslint:disable */
/* eslint-disable */
/**
 * Onboarding online screens graph models
 * Onboarding online screens graph models and interfaces
 *
 * The version of the OpenAPI document: 1.1.0-alpha.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Paywall body mask kind
 * @export
 */
export const PaywallBodyMaskKind = {
    PaywallBodyMaskKind1: 'PaywallBodyMaskKind1',
    PaywallBodyMaskKind2: 'PaywallBodyMaskKind2',
    PaywallBodyMaskKind3: 'PaywallBodyMaskKind3',
    PaywallBodyMaskKind4: 'PaywallBodyMaskKind4',
    PaywallBodyMaskKind5: 'PaywallBodyMaskKind5',
    PaywallBodyMaskKind6: 'PaywallBodyMaskKind6',
    PaywallBodyMaskKind7: 'PaywallBodyMaskKind7',
    PaywallBodyMaskKind8: 'PaywallBodyMaskKind8',
    PaywallBodyMaskKind9: 'PaywallBodyMaskKind9',
    PaywallBodyMaskKind10: 'PaywallBodyMaskKind10'
} as const;
export type PaywallBodyMaskKind = typeof PaywallBodyMaskKind[keyof typeof PaywallBodyMaskKind];


export function PaywallBodyMaskKindFromJSON(json: any): PaywallBodyMaskKind {
    return PaywallBodyMaskKindFromJSONTyped(json, false);
}

export function PaywallBodyMaskKindFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaywallBodyMaskKind {
    return json as PaywallBodyMaskKind;
}

export function PaywallBodyMaskKindToJSON(value?: PaywallBodyMaskKind | null): any {
    return value as any;
}

