/* tslint:disable */
/* eslint-disable */
/**
 * Onboarding online screens graph models
 * Onboarding online screens graph models and interfaces
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Paywall footer elements order
 * @export
 */
export const PaywallFooterElementsOrder = {
    PurchaseFirst: 'PurchaseFirst',
    AutoRenewLabelFirst: 'AutoRenewLabelFirst',
    PaywallFooterOrder1: 'PaywallFooterOrder1',
    PaywallFooterOrder2: 'PaywallFooterOrder2',
    PaywallFooterOrder3: 'PaywallFooterOrder3',
    PaywallFooterOrder4: 'PaywallFooterOrder4',
    PaywallFooterOrder5: 'PaywallFooterOrder5'
} as const;
export type PaywallFooterElementsOrder = typeof PaywallFooterElementsOrder[keyof typeof PaywallFooterElementsOrder];


export function PaywallFooterElementsOrderFromJSON(json: any): PaywallFooterElementsOrder {
    return PaywallFooterElementsOrderFromJSONTyped(json, false);
}

export function PaywallFooterElementsOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaywallFooterElementsOrder {
    return json as PaywallFooterElementsOrder;
}

export function PaywallFooterElementsOrderToJSON(value?: PaywallFooterElementsOrder | null): any {
    return value as any;
}

