/* tslint:disable */
/* eslint-disable */
/**
 * Onboarding online screens graph models
 * Onboarding online screens graph models and interfaces
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { NavLink } from './NavLink';
import {
    NavLinkFromJSON,
    NavLinkFromJSONTyped,
    NavLinkToJSON,
} from './NavLink';
import type { PaywallFooterBottomContainerBlock } from './PaywallFooterBottomContainerBlock';
import {
    PaywallFooterBottomContainerBlockFromJSON,
    PaywallFooterBottomContainerBlockFromJSONTyped,
    PaywallFooterBottomContainerBlockToJSON,
} from './PaywallFooterBottomContainerBlock';
import type { Text } from './Text';
import {
    TextFromJSON,
    TextFromJSONTyped,
    TextToJSON,
} from './Text';

/**
 * Paywall footer bottom container
 * @export
 * @interface PaywallFooterBottomContainer
 */
export interface PaywallFooterBottomContainer {
    /**
     * 
     * @type {NavLink}
     * @memberof PaywallFooterBottomContainer
     */
    privacyPolicy?: NavLink;
    /**
     * 
     * @type {Text}
     * @memberof PaywallFooterBottomContainer
     */
    restore?: Text;
    /**
     * 
     * @type {NavLink}
     * @memberof PaywallFooterBottomContainer
     */
    termsOfUse?: NavLink;
    /**
     * 
     * @type {PaywallFooterBottomContainerBlock}
     * @memberof PaywallFooterBottomContainer
     */
    styles: PaywallFooterBottomContainerBlock;
}

/**
 * Check if a given object implements the PaywallFooterBottomContainer interface.
 */
export function instanceOfPaywallFooterBottomContainer(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "styles" in value;

    return isInstance;
}

export function PaywallFooterBottomContainerFromJSON(json: any): PaywallFooterBottomContainer {
    return PaywallFooterBottomContainerFromJSONTyped(json, false);
}

export function PaywallFooterBottomContainerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaywallFooterBottomContainer {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'privacyPolicy': !exists(json, 'privacyPolicy') ? undefined : NavLinkFromJSON(json['privacyPolicy']),
        'restore': !exists(json, 'restore') ? undefined : TextFromJSON(json['restore']),
        'termsOfUse': !exists(json, 'termsOfUse') ? undefined : NavLinkFromJSON(json['termsOfUse']),
        'styles': PaywallFooterBottomContainerBlockFromJSON(json['styles']),
    };
}

export function PaywallFooterBottomContainerToJSON(value?: PaywallFooterBottomContainer | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'privacyPolicy': NavLinkToJSON(value.privacyPolicy),
        'restore': TextToJSON(value.restore),
        'termsOfUse': NavLinkToJSON(value.termsOfUse),
        'styles': PaywallFooterBottomContainerBlockToJSON(value.styles),
    };
}

