/* tslint:disable */
/* eslint-disable */
/**
 * Onboarding online screens graph models
 * Onboarding online screens graph models and interfaces
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PaywallFooterElementsOrder } from './PaywallFooterElementsOrder';
import {
    PaywallFooterElementsOrderFromJSON,
    PaywallFooterElementsOrderFromJSONTyped,
    PaywallFooterElementsOrderToJSON,
} from './PaywallFooterElementsOrder';

/**
 * Styles for paywall footer
 * @export
 * @interface PaywallFooterBlock
 */
export interface PaywallFooterBlock {
    /**
     * 
     * @type {PaywallFooterElementsOrder}
     * @memberof PaywallFooterBlock
     */
    elementsOrder?: PaywallFooterElementsOrder;
    /**
     * Background color for footer
     * @type {string}
     * @memberof PaywallFooterBlock
     */
    backgroundColor?: string;
    /**
     * 
     * @type {number}
     * @memberof PaywallFooterBlock
     */
    opacity?: number;
    /**
     * Padding left for container
     * @type {number}
     * @memberof PaywallFooterBlock
     */
    paddingLeft?: number;
    /**
     * Padding right for container
     * @type {number}
     * @memberof PaywallFooterBlock
     */
    paddingRight?: number;
    /**
     * Padding top for container
     * @type {number}
     * @memberof PaywallFooterBlock
     */
    paddingTop?: number;
    /**
     * Padding bottom for container
     * @type {number}
     * @memberof PaywallFooterBlock
     */
    paddingBottom?: number;
}

/**
 * Check if a given object implements the PaywallFooterBlock interface.
 */
export function instanceOfPaywallFooterBlock(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PaywallFooterBlockFromJSON(json: any): PaywallFooterBlock {
    return PaywallFooterBlockFromJSONTyped(json, false);
}

export function PaywallFooterBlockFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaywallFooterBlock {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'elementsOrder': !exists(json, 'elementsOrder') ? undefined : PaywallFooterElementsOrderFromJSON(json['elementsOrder']),
        'backgroundColor': !exists(json, 'backgroundColor') ? undefined : json['backgroundColor'],
        'opacity': !exists(json, 'opacity') ? undefined : json['opacity'],
        'paddingLeft': !exists(json, 'paddingLeft') ? undefined : json['paddingLeft'],
        'paddingRight': !exists(json, 'paddingRight') ? undefined : json['paddingRight'],
        'paddingTop': !exists(json, 'paddingTop') ? undefined : json['paddingTop'],
        'paddingBottom': !exists(json, 'paddingBottom') ? undefined : json['paddingBottom'],
    };
}

export function PaywallFooterBlockToJSON(value?: PaywallFooterBlock | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'elementsOrder': PaywallFooterElementsOrderToJSON(value.elementsOrder),
        'backgroundColor': value.backgroundColor,
        'opacity': value.opacity,
        'paddingLeft': value.paddingLeft,
        'paddingRight': value.paddingRight,
        'paddingTop': value.paddingTop,
        'paddingBottom': value.paddingBottom,
    };
}

