/* tslint:disable */
/* eslint-disable */
/**
 * Onboarding online screens graph models
 * Onboarding online screens graph models and interfaces
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Information about position on device in percentage
 * @export
 * @interface PositionOnDevice
 */
export interface PositionOnDevice {
    /**
     * x offset in percentage 0-100
     * @type {number}
     * @memberof PositionOnDevice
     */
    x: number;
    /**
     * y offset in percentage 0-100
     * @type {number}
     * @memberof PositionOnDevice
     */
    y: number;
}

/**
 * Check if a given object implements the PositionOnDevice interface.
 */
export function instanceOfPositionOnDevice(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "x" in value;
    isInstance = isInstance && "y" in value;

    return isInstance;
}

export function PositionOnDeviceFromJSON(json: any): PositionOnDevice {
    return PositionOnDeviceFromJSONTyped(json, false);
}

export function PositionOnDeviceFromJSONTyped(json: any, ignoreDiscriminator: boolean): PositionOnDevice {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'x': json['x'],
        'y': json['y'],
    };
}

export function PositionOnDeviceToJSON(value?: PositionOnDevice | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'x': value.x,
        'y': value.y,
    };
}

