/* tslint:disable */
/* eslint-disable */
/**
 * Onboarding online screens graph models
 * Onboarding online screens graph models and interfaces
 *
 * The version of the OpenAPI document: 1.1.0-alpha.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Information about position on configurator
 * @export
 * @interface PositionOnConfigurator
 */
export interface PositionOnConfigurator {
    /**
     * x coordinate
     * @type {number}
     * @memberof PositionOnConfigurator
     */
    x: number;
    /**
     * y coordinate
     * @type {number}
     * @memberof PositionOnConfigurator
     */
    y: number;
}

/**
 * Check if a given object implements the PositionOnConfigurator interface.
 */
export function instanceOfPositionOnConfigurator(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "x" in value;
    isInstance = isInstance && "y" in value;

    return isInstance;
}

export function PositionOnConfiguratorFromJSON(json: any): PositionOnConfigurator {
    return PositionOnConfiguratorFromJSONTyped(json, false);
}

export function PositionOnConfiguratorFromJSONTyped(json: any, ignoreDiscriminator: boolean): PositionOnConfigurator {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'x': json['x'],
        'y': json['y'],
    };
}

export function PositionOnConfiguratorToJSON(value?: PositionOnConfigurator | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'x': value.x,
        'y': value.y,
    };
}

