/* tslint:disable */
/* eslint-disable */
/**
 * Onboarding online screens graph models
 * Onboarding online screens graph models and interfaces
 *
 * The version of the OpenAPI document: 1.1.0-alpha.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LabelBlock } from './LabelBlock';
import {
    LabelBlockFromJSON,
    LabelBlockFromJSONTyped,
    LabelBlockToJSON,
} from './LabelBlock';

/**
 * Progress bar label element
 * @export
 * @interface ProgressBarLabel
 */
export interface ProgressBarLabel {
    /**
     * 
     * @type {LabelBlock}
     * @memberof ProgressBarLabel
     */
    styles: LabelBlock;
}

/**
 * Check if a given object implements the ProgressBarLabel interface.
 */
export function instanceOfProgressBarLabel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "styles" in value;

    return isInstance;
}

export function ProgressBarLabelFromJSON(json: any): ProgressBarLabel {
    return ProgressBarLabelFromJSONTyped(json, false);
}

export function ProgressBarLabelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProgressBarLabel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'styles': LabelBlockFromJSON(json['styles']),
    };
}

export function ProgressBarLabelToJSON(value?: ProgressBarLabel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'styles': LabelBlockToJSON(value.styles),
    };
}

