/* tslint:disable */
/* eslint-disable */
/**
 * Onboarding online screens graph models
 * Onboarding online screens graph models and interfaces
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Possible elements on regular list
 * @export
 */
export const RegularListItemBlockElement = {
    Image: 'Image',
    Title: 'Title'
} as const;
export type RegularListItemBlockElement = typeof RegularListItemBlockElement[keyof typeof RegularListItemBlockElement];


export function RegularListItemBlockElementFromJSON(json: any): RegularListItemBlockElement {
    return RegularListItemBlockElementFromJSONTyped(json, false);
}

export function RegularListItemBlockElementFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegularListItemBlockElement {
    return json as RegularListItemBlockElement;
}

export function RegularListItemBlockElementToJSON(value?: RegularListItemBlockElement | null): any {
    return value as any;
}

