/* tslint:disable */
/* eslint-disable */
/**
 * Onboarding online screens graph models
 * Onboarding online screens graph models and interfaces
 *
 * The version of the OpenAPI document: 1.1.0-alpha.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Tooltip } from './Tooltip';
import {
    TooltipFromJSON,
    TooltipFromJSONTyped,
    TooltipToJSON,
} from './Tooltip';

/**
 * Screen - Tooltip/Permissions
 * @export
 * @interface ScreenTooltipPermissionsAllOf
 */
export interface ScreenTooltipPermissionsAllOf {
    /**
     * 
     * @type {string}
     * @memberof ScreenTooltipPermissionsAllOf
     */
    tooltipPermissionsDescription: string;
    /**
     * 
     * @type {Tooltip}
     * @memberof ScreenTooltipPermissionsAllOf
     */
    tooltip: Tooltip;
}

/**
 * Check if a given object implements the ScreenTooltipPermissionsAllOf interface.
 */
export function instanceOfScreenTooltipPermissionsAllOf(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "tooltipPermissionsDescription" in value;
    isInstance = isInstance && "tooltip" in value;

    return isInstance;
}

export function ScreenTooltipPermissionsAllOfFromJSON(json: any): ScreenTooltipPermissionsAllOf {
    return ScreenTooltipPermissionsAllOfFromJSONTyped(json, false);
}

export function ScreenTooltipPermissionsAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScreenTooltipPermissionsAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tooltipPermissionsDescription': json['tooltipPermissionsDescription'],
        'tooltip': TooltipFromJSON(json['tooltip']),
    };
}

export function ScreenTooltipPermissionsAllOfToJSON(value?: ScreenTooltipPermissionsAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'tooltipPermissionsDescription': value.tooltipPermissionsDescription,
        'tooltip': TooltipToJSON(value.tooltip),
    };
}

