/* tslint:disable */
/* eslint-disable */
/**
 * Onboarding online screens graph models
 * Onboarding online screens graph models and interfaces
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Possible data types for input on screen
 * @export
 */
export const ScreenInputType = {
    String: 'string',
    Int: 'int',
    Double: 'double',
    Date: 'date',
    ListString: 'listString',
    ListInt: 'listInt',
    ListDouble: 'listDouble',
    ListDate: 'listDate'
} as const;
export type ScreenInputType = typeof ScreenInputType[keyof typeof ScreenInputType];


export function ScreenInputTypeFromJSON(json: any): ScreenInputType {
    return ScreenInputTypeFromJSONTyped(json, false);
}

export function ScreenInputTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScreenInputType {
    return json as ScreenInputType;
}

export function ScreenInputTypeToJSON(value?: ScreenInputType | null): any {
    return value as any;
}

