/* tslint:disable */
/* eslint-disable */
/**
 * Onboarding online screens graph models
 * Onboarding online screens graph models and interfaces
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BasicScreenBlock } from './BasicScreenBlock';
import {
    BasicScreenBlockFromJSON,
    BasicScreenBlockFromJSONTyped,
    BasicScreenBlockToJSON,
} from './BasicScreenBlock';
import type { Footer } from './Footer';
import {
    FooterFromJSON,
    FooterFromJSONTyped,
    FooterToJSON,
} from './Footer';
import type { Media } from './Media';
import {
    MediaFromJSON,
    MediaFromJSONTyped,
    MediaToJSON,
} from './Media';
import type { NavigationBar } from './NavigationBar';
import {
    NavigationBarFromJSON,
    NavigationBarFromJSONTyped,
    NavigationBarToJSON,
} from './NavigationBar';
import type { RequestPermission } from './RequestPermission';
import {
    RequestPermissionFromJSON,
    RequestPermissionFromJSONTyped,
    RequestPermissionToJSON,
} from './RequestPermission';
import type { ScreenTimer } from './ScreenTimer';
import {
    ScreenTimerFromJSON,
    ScreenTimerFromJSONTyped,
    ScreenTimerToJSON,
} from './ScreenTimer';
import type { Text } from './Text';
import {
    TextFromJSON,
    TextFromJSONTyped,
    TextToJSON,
} from './Text';
import type { TwoColumnSingleSelectionList } from './TwoColumnSingleSelectionList';
import {
    TwoColumnSingleSelectionListFromJSON,
    TwoColumnSingleSelectionListFromJSONTyped,
    TwoColumnSingleSelectionListToJSON,
} from './TwoColumnSingleSelectionList';

/**
 * 
 * @export
 * @interface ScreenTwoColumnSingleSelection
 */
export interface ScreenTwoColumnSingleSelection {
    /**
     * 
     * @type {NavigationBar}
     * @memberof ScreenTwoColumnSingleSelection
     */
    navigationBar: NavigationBar;
    /**
     * 
     * @type {Footer}
     * @memberof ScreenTwoColumnSingleSelection
     */
    footer: Footer;
    /**
     * 
     * @type {BasicScreenBlock}
     * @memberof ScreenTwoColumnSingleSelection
     */
    styles: BasicScreenBlock;
    /**
     * 
     * @type {RequestPermission}
     * @memberof ScreenTwoColumnSingleSelection
     */
    permission: RequestPermission | null;
    /**
     * 
     * @type {ScreenTimer}
     * @memberof ScreenTwoColumnSingleSelection
     */
    timer: ScreenTimer | null;
    /**
     * 
     * @type {boolean}
     * @memberof ScreenTwoColumnSingleSelection
     */
    animationEnabled: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ScreenTwoColumnSingleSelection
     */
    useLocalAssetsIfAvailable: boolean;
    /**
     * 
     * @type {string}
     * @memberof ScreenTwoColumnSingleSelection
     */
    twoColumnSingleSelectionDescription: string;
    /**
     * 
     * @type {Media}
     * @memberof ScreenTwoColumnSingleSelection
     */
    media?: Media;
    /**
     * 
     * @type {Text}
     * @memberof ScreenTwoColumnSingleSelection
     */
    title: Text;
    /**
     * 
     * @type {Text}
     * @memberof ScreenTwoColumnSingleSelection
     */
    subtitle: Text;
    /**
     * 
     * @type {TwoColumnSingleSelectionList}
     * @memberof ScreenTwoColumnSingleSelection
     */
    list: TwoColumnSingleSelectionList;
}

/**
 * Check if a given object implements the ScreenTwoColumnSingleSelection interface.
 */
export function instanceOfScreenTwoColumnSingleSelection(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "navigationBar" in value;
    isInstance = isInstance && "footer" in value;
    isInstance = isInstance && "styles" in value;
    isInstance = isInstance && "permission" in value;
    isInstance = isInstance && "timer" in value;
    isInstance = isInstance && "animationEnabled" in value;
    isInstance = isInstance && "useLocalAssetsIfAvailable" in value;
    isInstance = isInstance && "twoColumnSingleSelectionDescription" in value;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "subtitle" in value;
    isInstance = isInstance && "list" in value;

    return isInstance;
}

export function ScreenTwoColumnSingleSelectionFromJSON(json: any): ScreenTwoColumnSingleSelection {
    return ScreenTwoColumnSingleSelectionFromJSONTyped(json, false);
}

export function ScreenTwoColumnSingleSelectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScreenTwoColumnSingleSelection {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'navigationBar': NavigationBarFromJSON(json['navigationBar']),
        'footer': FooterFromJSON(json['footer']),
        'styles': BasicScreenBlockFromJSON(json['styles']),
        'permission': RequestPermissionFromJSON(json['permission']),
        'timer': ScreenTimerFromJSON(json['timer']),
        'animationEnabled': json['animationEnabled'],
        'useLocalAssetsIfAvailable': json['useLocalAssetsIfAvailable'],
        'twoColumnSingleSelectionDescription': json['twoColumnSingleSelectionDescription'],
        'media': !exists(json, 'media') ? undefined : MediaFromJSON(json['media']),
        'title': TextFromJSON(json['title']),
        'subtitle': TextFromJSON(json['subtitle']),
        'list': TwoColumnSingleSelectionListFromJSON(json['list']),
    };
}

export function ScreenTwoColumnSingleSelectionToJSON(value?: ScreenTwoColumnSingleSelection | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'navigationBar': NavigationBarToJSON(value.navigationBar),
        'footer': FooterToJSON(value.footer),
        'styles': BasicScreenBlockToJSON(value.styles),
        'permission': RequestPermissionToJSON(value.permission),
        'timer': ScreenTimerToJSON(value.timer),
        'animationEnabled': value.animationEnabled,
        'useLocalAssetsIfAvailable': value.useLocalAssetsIfAvailable,
        'twoColumnSingleSelectionDescription': value.twoColumnSingleSelectionDescription,
        'media': MediaToJSON(value.media),
        'title': TextToJSON(value.title),
        'subtitle': TextToJSON(value.subtitle),
        'list': TwoColumnSingleSelectionListToJSON(value.list),
    };
}

