/* tslint:disable */
/* eslint-disable */
/**
 * Onboarding online screens graph models
 * Onboarding online screens graph models and interfaces
 *
 * The version of the OpenAPI document: 1.1.0-alpha.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Image } from './Image';
import {
    ImageFromJSON,
    ImageFromJSONTyped,
    ImageToJSON,
} from './Image';
import type { Picker } from './Picker';
import {
    PickerFromJSON,
    PickerFromJSONTyped,
    PickerToJSON,
} from './Picker';
import type { Text } from './Text';
import {
    TextFromJSON,
    TextFromJSONTyped,
    TextToJSON,
} from './Text';

/**
 * Screen - Image/Title/Subtitle/Picker
 * @export
 * @interface ScreenImageTitleSubtitlePickerAllOf
 */
export interface ScreenImageTitleSubtitlePickerAllOf {
    /**
     * 
     * @type {string}
     * @memberof ScreenImageTitleSubtitlePickerAllOf
     */
    imageTitleSubtitlePickerDescription: string;
    /**
     * 
     * @type {Image}
     * @memberof ScreenImageTitleSubtitlePickerAllOf
     */
    image: Image;
    /**
     * 
     * @type {Text}
     * @memberof ScreenImageTitleSubtitlePickerAllOf
     */
    title: Text;
    /**
     * 
     * @type {Text}
     * @memberof ScreenImageTitleSubtitlePickerAllOf
     */
    subtitle: Text;
    /**
     * 
     * @type {Picker}
     * @memberof ScreenImageTitleSubtitlePickerAllOf
     */
    picker: Picker;
}

/**
 * Check if a given object implements the ScreenImageTitleSubtitlePickerAllOf interface.
 */
export function instanceOfScreenImageTitleSubtitlePickerAllOf(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "imageTitleSubtitlePickerDescription" in value;
    isInstance = isInstance && "image" in value;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "subtitle" in value;
    isInstance = isInstance && "picker" in value;

    return isInstance;
}

export function ScreenImageTitleSubtitlePickerAllOfFromJSON(json: any): ScreenImageTitleSubtitlePickerAllOf {
    return ScreenImageTitleSubtitlePickerAllOfFromJSONTyped(json, false);
}

export function ScreenImageTitleSubtitlePickerAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScreenImageTitleSubtitlePickerAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'imageTitleSubtitlePickerDescription': json['imageTitleSubtitlePickerDescription'],
        'image': ImageFromJSON(json['image']),
        'title': TextFromJSON(json['title']),
        'subtitle': TextFromJSON(json['subtitle']),
        'picker': PickerFromJSON(json['picker']),
    };
}

export function ScreenImageTitleSubtitlePickerAllOfToJSON(value?: ScreenImageTitleSubtitlePickerAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'imageTitleSubtitlePickerDescription': value.imageTitleSubtitlePickerDescription,
        'image': ImageToJSON(value.image),
        'title': TextToJSON(value.title),
        'subtitle': TextToJSON(value.subtitle),
        'picker': PickerToJSON(value.picker),
    };
}

