/* tslint:disable */
/* eslint-disable */
/**
 * Onboarding online screens graph models
 * Onboarding online screens graph models and interfaces
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RgbaShadowMask } from './RgbaShadowMask';
import {
    RgbaShadowMaskFromJSON,
    RgbaShadowMaskFromJSONTyped,
    RgbaShadowMaskToJSON,
} from './RgbaShadowMask';

/**
 * Styles for ScreenBasicPaywall
 * @export
 * @interface ScreenBasicPaywallBlockAllOf
 */
export interface ScreenBasicPaywallBlockAllOf {
    /**
     * 
     * @type {string}
     * @memberof ScreenBasicPaywallBlockAllOf
     */
    bodyColor?: string;
    /**
     * 
     * @type {string}
     * @memberof ScreenBasicPaywallBlockAllOf
     */
    bodyOpacity?: string;
    /**
     * 
     * @type {RgbaShadowMask}
     * @memberof ScreenBasicPaywallBlockAllOf
     */
    bodyShadowMask?: RgbaShadowMask;
}

/**
 * Check if a given object implements the ScreenBasicPaywallBlockAllOf interface.
 */
export function instanceOfScreenBasicPaywallBlockAllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ScreenBasicPaywallBlockAllOfFromJSON(json: any): ScreenBasicPaywallBlockAllOf {
    return ScreenBasicPaywallBlockAllOfFromJSONTyped(json, false);
}

export function ScreenBasicPaywallBlockAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScreenBasicPaywallBlockAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bodyColor': !exists(json, 'bodyColor') ? undefined : json['bodyColor'],
        'bodyOpacity': !exists(json, 'bodyOpacity') ? undefined : json['bodyOpacity'],
        'bodyShadowMask': !exists(json, 'bodyShadowMask') ? undefined : RgbaShadowMaskFromJSON(json['bodyShadowMask']),
    };
}

export function ScreenBasicPaywallBlockAllOfToJSON(value?: ScreenBasicPaywallBlockAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'bodyColor': value.bodyColor,
        'bodyOpacity': value.bodyOpacity,
        'bodyShadowMask': RgbaShadowMaskToJSON(value.bodyShadowMask),
    };
}

