/* tslint:disable */
/* eslint-disable */
/**
 * Onboarding online screens graph models
 * Onboarding online screens graph models and interfaces
 *
 * The version of the OpenAPI document: 1.1.0-alpha.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Combination of fields for subscription list item
 * @export
 */
export const SubscriptionListItemType = {
    CheckboxLabels: 'CheckboxLabels',
    LabelsCheckbox: 'LabelsCheckbox',
    SubscriptionListItemType1: 'SubscriptionListItemType1',
    SubscriptionListItemType2: 'SubscriptionListItemType2',
    SubscriptionListItemType3: 'SubscriptionListItemType3',
    SubscriptionListItemType4: 'SubscriptionListItemType4',
    SubscriptionListItemType5: 'SubscriptionListItemType5',
    SubscriptionListItemType6: 'SubscriptionListItemType6',
    SubscriptionListItemType7: 'SubscriptionListItemType7',
    SubscriptionListItemType8: 'SubscriptionListItemType8',
    SubscriptionListItemType9: 'SubscriptionListItemType9',
    SubscriptionListItemType10: 'SubscriptionListItemType10'
} as const;
export type SubscriptionListItemType = typeof SubscriptionListItemType[keyof typeof SubscriptionListItemType];


export function SubscriptionListItemTypeFromJSON(json: any): SubscriptionListItemType {
    return SubscriptionListItemTypeFromJSONTyped(json, false);
}

export function SubscriptionListItemTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionListItemType {
    return json as SubscriptionListItemType;
}

export function SubscriptionListItemTypeToJSON(value?: SubscriptionListItemType | null): any {
    return value as any;
}

