/* tslint:disable */
/* eslint-disable */
/**
 * Onboarding online screens graph models
 * Onboarding online screens graph models and interfaces
 *
 * The version of the OpenAPI document: 1.1.0-alpha.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Tooltip image position
 * @export
 */
export const TooltipImagePosition = {
    Top: 'top',
    Bottom: 'bottom',
    Left: 'left',
    Right: 'right'
} as const;
export type TooltipImagePosition = typeof TooltipImagePosition[keyof typeof TooltipImagePosition];


export function TooltipImagePositionFromJSON(json: any): TooltipImagePosition {
    return TooltipImagePositionFromJSONTyped(json, false);
}

export function TooltipImagePositionFromJSONTyped(json: any, ignoreDiscriminator: boolean): TooltipImagePosition {
    return json as TooltipImagePosition;
}

export function TooltipImagePositionToJSON(value?: TooltipImagePosition | null): any {
    return value as any;
}

