/* tslint:disable */
/* eslint-disable */
/**
 * Onboarding online screens graph models
 * Onboarding online screens graph models and interfaces
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Styles for video
 * @export
 * @interface VideoBlock
 */
export interface VideoBlock {
    /**
     * width of video
     * @type {number}
     * @memberof VideoBlock
     */
    width?: number;
    /**
     * height of video
     * @type {number}
     * @memberof VideoBlock
     */
    height?: number;
}

/**
 * Check if a given object implements the VideoBlock interface.
 */
export function instanceOfVideoBlock(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VideoBlockFromJSON(json: any): VideoBlock {
    return VideoBlockFromJSONTyped(json, false);
}

export function VideoBlockFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoBlock {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'width': !exists(json, 'width') ? undefined : json['width'],
        'height': !exists(json, 'height') ? undefined : json['height'],
    };
}

export function VideoBlockToJSON(value?: VideoBlock | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'width': value.width,
        'height': value.height,
    };
}

